### Import Libraries

In [2]:
# import the necessary packages
from os import listdir
from os.path import isfile , join
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np

### Let's make a function to convert RGB images to Grayscale

In [3]:
def rgb2gray(rgb_image):
    return np.dot(rgb_image[...,:3], [0.299, 0.587, 0.114])
#images[0][0,2,:3] ##?? images[0][...,:] ## images[0][0,2,:2] ##

### And a function to convert grayscale to binary images

In [4]:
def binarize( gray_image , threshold ):
    threshold = np.max( gray_image ) * threshold
    return 1 * ( gray_image > threshold )

### A function to show multiple images in a single figure

In [5]:
def multi_view( images ):
    images_count = len( images ) #count of images (list type)
    fig = plt.figure(figsize=(10,20))
    for row in range( images_count  ):
        ax1 = fig.add_subplot( images_count , 1 , row + 1)
        #ax1.imshow( images[ row ] )
        ax1.imshow(images[ row ], cmap=plt.get_cmap('gray')) # default is viridis 

In [6]:
def view( image ):
    plt.figure(figsize=(10,20))
    #plt.imshow( image )
    plt.imshow(image, cmap=plt.get_cmap('gray'), vmin=0, vmax=1)

## 1. Load Images

In [7]:

# Get file names in current directory
images_files = [ join("./images" , f) for f in listdir("images") if isfile(join("images" , f)) ]

images = [ mpimg.imread( f ) for f in images_files ]
print(type(images))
print(len(images[0]))
len(images)

<class 'list'>
393


7

In [8]:
len(images) # length of the list; six images

7

In [9]:
print('Number of rows is len(images[1]) and is equal to:       ',len(images[1])) # Num rows
print('Number of columns is len(images[1][0]) and is equal to: ',len(images[1][0])) # Num columns

Number of rows is len(images[1]) and is equal to:        265
Number of columns is len(images[1][0]) and is equal to:  264


## 2. Make Grayscale Images

In [16]:
gray_images = [ rgb2gray( img ) for img in images ]
#gray_images[0]>.3

array([[0, 1, 0, ..., 1, 1, 1],
       [1, 0, 1, ..., 1, 1, 1],
       [0, 1, 0, ..., 1, 1, 1],
       ...,
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]])

## 3. Make Binary Images

In [11]:
binary_images = [ binarize( gray_img , 0.5 ) for gray_img in gray_images ]


## 4. View Images

In [12]:
#X1 = ('a','b','c')
#X2 = (1,2,3)
#X3=[(0,1),(10,1),(5,1)]
#Y = zip(X1, X2,X3) #tuple
#YList=list(zip(X1, X2,X3))
#print(Y) ##
#print(YList)
#print(Y.__sizeof__())
#print(YList.__sizeof__())

In [13]:
combinations = list( zip( images , gray_images , binary_images ))
#print(len(combinations)) #Number of sets of images 6
#print(len(combinations[0])) #Number of images per set Note the print command
#print(len(combinations[0])) #Number of images per set; without print; it displays the last call only
#[multi_view( comb ) for comb in combinations]
#multi_view(combinations[0])

In [14]:
#x = np.arange(10) #0:9
#x2 = np.reshape(x, (2,5)) #0:4, 5:9
x3=np.array([(1,2,3),(4,5,6),(-1,-2,-3),(-4,-5,-6)])
print(x3)
#print(len(x3)) # 4 rows
#print(len(x3[0]))# 3 columns
print(np.roll(x3,1,1)) # Right shift by one for Columns
#print(np.roll(x3,1,0)) # Down shift by one for Rows
#print(np.roll(x3,1,2)) # ERROR..Why
print(np.roll(x3,-1,1)) # Left shift by one for Columns
print(np.roll(x3,-1,0)) # Up shift by one for Rows

[[ 1  2  3]
 [ 4  5  6]
 [-1 -2 -3]
 [-4 -5 -6]]
[[ 3  1  2]
 [ 6  4  5]
 [-3 -1 -2]
 [-6 -4 -5]]
[[ 2  3  1]
 [ 5  6  4]
 [-2 -3 -1]
 [-5 -6 -4]]
[[ 4  5  6]
 [-1 -2 -3]
 [-4 -5 -6]
 [ 1  2  3]]
